name: Starter Pipeline for Java Gradle Project using Github Packages

on: 
 push:
    branches: [ fod_test ]

   
  #push:
    #branches: [ branch-java-gradle-sample ]

######  Please Make sure you have the secrets setup in ################

#  SAML_GITHUB_TOKEN --> PAT of Y account to connect to repository [required]
#  SAML_GITHUB_USER --> Y account user name, [required] to authenticate github artifacts

#  #####Secrets for running Code Quality#####
#  SONAR_PROJECT_NAME
#  SONAR_PROJECT_KEY
#  SONAR_TOKEN

#  secrets used for APP-SEC scan 
# SNYK_API_TOKEN

# FORTIFY_RELEASE_ID
# FORTIFY_CLIENT_ID
# FORTIFY_CLIENT_SECRET

# PRISMA_URL  -- already setup as a environement variable
# PRISMA_ACCESS_KEY_ID 
# PRISMA_SECRET_KEY

#### Secrets for webapp Deployment
# AZURE_WEBAPP_NAME
# AZURE_WEBAPP_PUBLISH_PROFILE {if you have been provided with one}

#### Secrets for Helm Deployment
# KUBE_CONFIG

# Secretes for setting up New relic Deployment Marker and Insights.
# The starter script uses the secrect under environment : Non-prod.
# NEW_RELIC_API_KEY
# NEW_RELIC_ACCOUNT_ID
# NEW_RELIC_APP_ID


# set GLOBAL environment variable to be used in the workflow and reference using ${{env.name_declared}}
env:
  # CI CD PARAMETERS
  APPLICATION_NAME: java-gradlestarter
  environment: dev
  SONAR_CLOUD_URL: https://sonarcloud.io
  GH_REGISTRY: ghcr.io/${{github.repository}} 
  CONTAINER_IMAGE_NAME: java-gradlestarter-webapp-sample
  image_tag: ${{ github.run_number }}
  Chart: helm-sample-java #Update based on the helm chart folder
  CLUSTER_NAMESPACE: sample-app
  PRISMA_URL: https://europe-west3.cloud.twistlock.com/eu-2-143543845
  SP_TENANT_ID: bd5c6713-7399-4b31-be79-78f2d078e543
  
jobs:
  FOD_scans:
    environment: Non-prod
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
      with:
        repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Java
        token: ${{ secrets.SAML_GITHUB_TOKEN }}
        ref: branch-java-gradle-sample
    - name: Download Fortify on Demand Universal CI Tool
      uses: fortify/gha-setup-fod-uploader@v1
    - run: |
        zip -r technology-clouddevops_fortify.zip . 
        java -jar $FOD_UPLOAD_JAR -uc 'Y9886988@marks-and-spencer.com' ${{ secrets.FOD_PAT }} -rid 6560 -purl 'https://emea.fortify.com/' -apiurl 'https://api.emea.fortify.com/' -z technology-clouddevops_fortify.zip} -ep 2 -rp 0 -pp 1 -apf -I 1
        status=$?
        echo $status
        if test $status -eq 1
        then
          echo "scan is successful"
        else
          exit 1 
        fi
